### ISSUE TITLE
HTTP2 support for some services

### ISSUE THREAD

**Issue by svroonland** [zio/zio-aws#109]
For my zio-kinesis project I'm using the Kinesis, DynamoDB and CloudWatch SDKs. Some Kinesis feature (enhanced fanout) requires HTTP2, but the others don't support it currently, resulting in connection errors.

Currently I have a custom ZLayer which can be created with many client parameters like timeout and max nr of connections. It defines a service that exposes a _function_ to create the actual client, with a parameter `http2Supported `.

See https://github.com/svroonland/zio-kinesis/pull/224/files#diff-7319031fce96ba26a9a0a00e28b6ef2d3d9c35141f6d44b8ce2a74cac722990aL8

Perhaps there is a better way to support this kind of functionality?

**Comment by svroonland** [comment]
One thing that would already help is being able to create one of the clients as a `ZManaged`. Then I can do something like

```scala
ZLayer.fromServiceManaged { httpClientBuilder => 
  kinesis.customizedM(_.httpClient(httpClientBuilder.createSdkHttpClient(http2Supported = true)))
}
```

**Comment by vigoo** [comment]
@svroonland can we close this, or think about some even better support?

**Comment by svroonland** [comment]
The solution I made does not have the HttpClient and Config layers, but somethign custom. So if there would be a way to do this, that would be great. Perhaps it's a problem that should be solved at the SDK level though.
