### ISSUE TITLE
Enforce AWS Cloudfront to ignore region 

### ISSUE THREAD

**Issue by GermanSmoliar** [zio/zio-aws#1107]
Since AWS CloudFront is global region service it should be set to AWS_GLOBAL by default otherwise HTTP request URL is wrong.

Steps to reproduce:

Set config like: 

```
  val commonAwsConfig = ZLayer.succeed(
    CommonAwsConfig(
      region = Some(Region.US_EAST_1),
      credentialsProvider = DefaultCredentialsProvider.create(),
      endpointOverride = None,
      commonClientConfig = None
    )
  )
```
Try to submit any request. (eg cache invalidation)

Getting error: 

`http4s.client.ConnectionFailure: Error connecting to https://cloudfront.us-east-1.amazonaws.com using address cloudfront.us-east-1.amazonaws.com:443 
`

If region is set to `Region.AWS_GLOBAL` url will be:  `https://cloudfront.amazonaws.com`

**Comment by vigoo** [comment]
Based on https://docs.aws.amazon.com/general/latest/gr/rande.html the following services have only global endpoints:

- Amazon CloudFront
- AWS Global Accelerator
- AWS Identity and Access Management (IAM)
- AWS Network Manager
- AWS Organizations
- Amazon Route 53
- AWS Shield Advanced
- AWS WAF Classic

This information is not available in the schema - for example here https://github.com/aws/aws-sdk-java-v2/blob/master/services/cloudfront/src/main/resources/codegen-resources/endpoint-rule-set.json they define per-region endpoints as well even though it is not how it works.

So I think we should hard-code the above list in the generator and provide a different default config for those services.
