### ISSUE TITLE
Easy way to create read only version of model objects

### ISSUE THREAD

**Issue by svroonland** [zio/zio-aws#117]
Something like a `.readOnly` method would be nice to create model objects for use in tests. 
Now you have to do something like `BatchResultErrorEntry.wrap(BatchResultErrorEntry("id1").buildAwsValue())`

**Comment by vigoo** [comment]
Originally the model classes implemented the `ReadOnly` trait, but I broke that when introduced the effectful getters. So this is definitely missing!
