### ISSUE TITLE
SDK version update

### ISSUE THREAD

**Issue by gipeshka** [zio/zio-aws#1323]
Hey guys, how are you?

I've spotted that the lib is using AWS SDK `2.21.15`. Looks like there exists already `2.27.5` and there's a BC break introduced somewhere in between (a protected method `setOverrides` is now final). Which makes it a bit uncomfortable to use the lib if an new SDK version is also present.

Thus the question, do you guys have any plans updating the SDK version?

Thanks.

**Comment by calvinlfer** [comment]
Think we can close this

**Comment by gipeshka** [comment]
Thanks!
