### ISSUE TITLE
Can you publish for scala 2.12 as well as 2.13?

### ISSUE THREAD

**Issue by dpennell** [zio/zio-aws#2]

**Comment by dpennell** [comment]
BTW - this is a really awesome set of libraries.  Working with the aws java libs is horrible

**Comment by vigoo** [comment]
Hi, I can do it next week!

**Comment by vigoo** [comment]
Prepared in the above PR, I will generate and publish 2.12 versions too next time (I plan to do a new release containing other changes as well this week)

**Comment by dpennell** [comment]
Thanks!
