### ISSUE TITLE
Generated aws-ssm artifacts is empty

### ISSUE THREAD

**Issue by EtaCassiopeia** [zio/zio-aws#263]
Generated zio-aws-ssm artifact is an empty jar and it contains nothing but an empty MANIFEST file.

**Comment by vigoo** [comment]
Thanks for reporting!

Seems like an AWS SDK update broke it and now code generator fails with 
```
InvalidPaginatedOperation(ssm,ListDocumentMetadataHistory)
```

TODO:

- [x] Investigate and fix the issue
- [x] Code generator failures should break the build so breaking updates cannot be merged

**Comment by vigoo** [comment]
Also fails on `InvalidPaginatedOperation(devopsguru,GetResourceCollection)`
