### ISSUE TITLE
Remove default async executor threadpool 

### ISSUE THREAD

**Issue by svroonland** [zio/zio-aws#364]
See https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/asynchronous.html#advanced-operations and https://stackoverflow.com/questions/62472073/asyncfuturecompletionexecutor-vs-netty-event-loop

I believe we don't need this executor + extra thread pool in `zio-aws`, since we immediately callback into the ZIO runtime. It will increase performance somewhat by having less threads and less context switching.

I suggest incorporating this in the default client configs:

```scala
        override def configureHttpClient[Client, Builder <: AwsAsyncClientBuilder[Builder, Client]](
          builder: Builder,
          serviceCaps: httpclient.ServiceHttpCapabilities
        ): Task[Builder] = 
          ZIO.executor.map { executor =>
            builder
              .asyncConfiguration(
                ClientAsyncConfiguration
                  .builder()
                  .advancedOption(
                    SdkAdvancedAsyncClientOption.FUTURE_COMPLETION_EXECUTOR,
                    executor.asJava
                  )
                  .build()
              )
          }

```

**Comment by svroonland** [comment]
Updated, using the ZIO executor shows better performance.

**Comment by vigoo** [comment]
Nice find! I agree we should have this in the default configuration
