### ISSUE TITLE
Adopt to change in embedding codegen resources in the Java SDK JARs

### ISSUE THREAD

**Issue by vigoo** [zio/zio-aws#715]
See https://github.com/aws/aws-sdk-java-v2/issues/3022

**Comment by millems** [comment]
We're currently in the process of moving to https://awslabs.github.io/smithy/, which means that the C2J (what we call the service-2.json files) resources are going away in the medium term. 

Design-wise, it's probably better to rely on the service models not being available at runtime, but asking you to pull them from random directories in our repo isn't exactly a great experience, either. 

Let me reach out to the smithy teams to see if there's a good way to make the models available for your project.

**Comment by vigoo** [comment]
Thanks @millems, eventually I would also like to switch to smithy but not there yet. Currently the service models are used only during this library's build, not runtime, but it was very easy to gather them by depending on the full `aws-sdk-java` bundle and extracting its resources. Then it uses the service models to generate wrappers on top of the Java library so it does not have to deal with details of the protocol and special cases - if the wrapper compiles then we know it works, trusting the underlying Java library.

With moving to Smithy in the future it will be probably easier to just directly rely on the smithy models for generating the serialization and protocol code too instead of wrapping the Java SDK.

Is there already a full smithy specification for the whole set of services covered by AWS Java SDK v2?

**Comment by millems** [comment]
Right now there are a few SDKs generated from the smithy models. For example, the Kotlin SDK has those models stored here: https://github.com/awslabs/aws-sdk-kotlin/tree/main/codegen/sdk/aws-models. I believe the format is nearly completely documented here: https://awslabs.github.io/smithy/1.0/spec/index.html. Certainly better than the C2j is documented.

I don't know a great way to distribute the models. What would be your preferred way of consuming it? Actually having us package them up into a jar like was done in the past?

**Comment by vigoo** [comment]
Publishing them in a jar to Maven Central has the advantage that tools like Scala Steward automatically detect it and open a PR with the update for the repo. (You can see that we are releasing a new zio-aws for each AWS Java SDK v2 build basically daily)

That said, if there is an official repository of all the smithy specs and that gets regularly tagged with new versions that would be also completely fine, just have to implement a CI task that watches the repo, and change the code generator to fetch from there.
